"""
bot/services - Lógica compartida para handlers del bot.
"""
from .db import *  # noqa: F403,F401
from .ai import *  # noqa: F403,F401
from .tts import (  # noqa: F403,F401
    generar_audio_respuesta,
    _limpiar_marca_tts,
)

__all__ = [
    # db
    "guardar_mensaje",
    "obtener_tareas_pendientes",
    "marcar_tarea_completada",
    "obtener_balance_financiero",
    "obtener_resumen_presupuestos",
    "registrar_transaccion_v2",
    "obtener_balance_v2",
    "obtener_presupuestos_v2",
    "listar_cuentas",
    "crear_cuenta",
    "actualizar_presupuesto_categoria",
    "registrar_transferencia",
    "listar_metas_v2",
    "guardar_meta_v2",
    "agregar_aporte_meta",
    "listar_recurrentes",
    "guardar_recurrente",
    "obtener_alertas_presupuesto",
    "obtener_estadisticas",
    "crear_categorias_predefinidas",
    "listar_transacciones_recientes",
    "crear_subcategoria",
    "listar_subcategorias",
    "crear_subcategorias_predefinidas",
    "registrar_split",
    "registrar_transaccion_futura",
    "listar_transacciones_futuras",
    "buscar_transacciones",
    "aplicar_rollover_presupuesto",
    "guardar_recordatorio",
    "listar_recordatorios",
    "obtener_recordatorios_hoy",
    "marcar_recordatorio_hecho",
    "obtener_sugerencias_payee",
    "obtener_sugerencias_categoria",
    "guardar_tasa_cambio",
    "obtener_tasas_cambio",
    "convertir_monto",
    "obtener_balance_total_multimoneda",
    "guardar_tarea",
    "registrar_transaccion",
    "establecer_presupuesto",
    "guardar_meta",
    "obtener_metas",
    "eliminar_meta",
    "actualizar_progreso_meta",
    "proyectar_meta",
    "modificar_presupuesto",
    "guardar_pago_fijo",
    "obtener_pagos_fijos",
    "eliminar_pago_fijo",
    "guardar_perfil",
    "obtener_perfil",
    "inicializar_firebase",
    "db",
    # ai
    "procesar_intencion_natural",
    "pensar_respuesta",
    "pensar_respuesta_audio",
    "pensar_respuesta_imagen",
    "analizar_inversion",
    "transcribir_audio",
    "_API_KEYS",
    "_key_index",
    "_esperar_por_rpm",
    "_gemini_call_with_fallback",
    # tts
    "generar_audio_respuesta",
    "_limpiar_marca_tts",
]